name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code 🛎
        uses: actions/checkout@v6
      - name: Install dependencies 📦
        uses: bahmutov/npm-install@v1

      - name: Run demo
        run: |
          npm run stop-only
          npm run warn-only

      - name: Run unit tests 🧪
        run: npm test

      - name: Semantic Release 🚀
        if: github.ref == 'refs/heads/master'
        uses: cycjimmy/semantic-release-action@v3
        with:
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
